import React from 'react';
import { StyleSheet, Text, View, ScrollView } from 'react-native';

const INFO_ITEMS = [
  {
    icon: '◈',
    color: '#00F5FF',
    title: 'ALGORITHMIC_SCORE',
    description:
      'A cryptographic trust score from 0–100 is generated by analyzing the wallet age, transaction history, and community votes.',
  },
  {
    icon: '⬡',
    color: '#00FF88',
    title: 'ON-CHAIN_ATTESTATION',
    description:
      'Each query result is logged with a simulated TX hash and block number, as if read from the Ethereum blockchain.',
  },
  {
    icon: '⚠',
    color: '#FFE600',
    title: 'RISK_ANALYSIS',
    description:
      'The score is automatically penalized when suspicious address contacts, abnormal txCount, or bot behaviors are detected.',
  },
  {
    icon: '◉',
    color: '#C084FC',
    title: 'COMMUNITY_PROTOCOL',
    description:
      'Trust votes given by verified nodes positively impact the final score.',
  },
  {
    icon: '⊕',
    color: '#FF0066',
    title: 'ADDRESS_SCAN',
    description:
      'You can query any Ethereum address from the main screen. Demo nodes are available for quick testing.',
  },
];

const SCORE_LEVELS = [
  { label: 'TRUSTED', range: '70–100', color: '#00FF88', glow: 'rgba(0,255,136,0.3)' },
  { label: 'MEDIUM', range: '40–69', color: '#FFE600', glow: 'rgba(255,230,0,0.3)' },
  { label: 'RISKY', range: '0–39', color: '#FF0066', glow: 'rgba(255,0,102,0.3)' },
];

export default function ExploreScreen() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Grid çizgileri */}
      <View style={styles.gridOverlay} pointerEvents="none">
        {Array.from({ length: 10 }).map((_, i) => (
          <View key={i} style={[styles.gridLine, { top: i * 110 }]} />
        ))}
      </View>

      <View style={styles.header}>
        <Text style={styles.headerTag}>{'// SYSTEM_DOCUMENTATION'}</Text>
        <Text style={styles.title}>
          HOW_IT<Text style={styles.titleAccent}>_WORKS</Text>
        </Text>
        <Text style={styles.subtitle}>trustlayer_protocol_v1.0 · docs</Text>
        <View style={styles.titleUnderline} />
      </View>

      {INFO_ITEMS.map((item, index) => (
        <View key={index} style={[styles.card, { borderLeftColor: item.color }]}>
          <View style={styles.cardHeader}>
            <Text style={[styles.cardIcon, { color: item.color, textShadowColor: item.color }]}>
              {item.icon}
            </Text>
            <Text style={[styles.cardTitle, { color: item.color }]}>{item.title}</Text>
          </View>
          <Text style={styles.cardDescription}>{item.description}</Text>
        </View>
      ))}

      {/* Skor seviyeleri */}
      <View style={styles.levelSection}>
        <View style={styles.levelHeader}>
          <View style={styles.levelDot} />
          <Text style={styles.levelSectionTitle}>SCORE_LEVELS</Text>
        </View>
        {SCORE_LEVELS.map((level) => (
          <View key={level.label} style={styles.levelRow}>
            <View style={[styles.levelBadge, { borderColor: level.color, backgroundColor: level.glow }]}>
              <Text style={[styles.levelRange, { color: level.color }]}>{level.range}</Text>
            </View>
            <View style={[styles.levelBar, { backgroundColor: level.color, opacity: 0.15 }]} />
            <Text style={[styles.levelLabel, { color: level.color }]}>{level.label}</Text>
          </View>
        ))}
      </View>

      {/* Versiyon footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>{'> trustlayer_core v1.0.0 · MIT License'}</Text>
        <Text style={styles.footerText}>{'> node: MAINNET · latency: ~12s/block'}</Text>
      </View>

      <View style={{ height: 100 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#050810' },
  content: { paddingHorizontal: 20 },
  gridOverlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0,
  },
  gridLine: {
    position: 'absolute', left: 0, right: 0, height: 1,
    backgroundColor: 'rgba(0, 245, 255, 0.04)',
  },
  header: {
    marginTop: 70,
    marginBottom: 28,
    zIndex: 1,
  },
  headerTag: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: '#2A4A6A',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  title: {
    fontSize: 36,
    fontWeight: '900',
    color: '#D0E8FF',
    letterSpacing: 3,
  },
  titleAccent: {
    color: '#C084FC',
    textShadowColor: 'rgba(192, 132, 252, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  subtitle: {
    fontSize: 11,
    color: '#2A4A6A',
    fontFamily: 'monospace',
    marginTop: 6,
    letterSpacing: 1,
  },
  titleUnderline: {
    marginTop: 14,
    height: 1,
    backgroundColor: '#C084FC',
    width: 50,
    shadowColor: '#C084FC',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  // Kart
  card: {
    backgroundColor: '#070D1A',
    borderRadius: 4,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#1A2A4A',
    borderLeftWidth: 3,
    zIndex: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  cardIcon: {
    fontSize: 18,
    fontWeight: '700',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: '800',
    fontFamily: 'monospace',
    letterSpacing: 1.5,
  },
  cardDescription: {
    fontSize: 13,
    color: '#4A6A8A',
    lineHeight: 20,
    fontFamily: 'monospace',
  },
  // Skor seviyeleri
  levelSection: {
    backgroundColor: '#070D1A',
    borderRadius: 4,
    padding: 18,
    borderWidth: 1,
    borderColor: '#1A2A4A',
    marginBottom: 16,
    zIndex: 1,
  },
  levelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  levelDot: {
    width: 6, height: 6, borderRadius: 1,
    backgroundColor: '#00F5FF',
    shadowColor: '#00F5FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1, shadowRadius: 4,
  },
  levelSectionTitle: {
    fontSize: 10, fontWeight: '800', color: '#00F5FF',
    fontFamily: 'monospace', letterSpacing: 1.5, opacity: 0.8,
  },
  levelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 10,
  },
  levelBadge: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 2,
    minWidth: 68,
    alignItems: 'center',
  },
  levelRange: {
    fontFamily: 'monospace',
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 1,
  },
  levelBar: {
    flex: 1,
    height: 1,
  },
  levelLabel: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: '800',
    letterSpacing: 1.5,
    minWidth: 70,
    textAlign: 'right',
  },
  // Footer
  footer: {
    borderTopWidth: 1,
    borderTopColor: '#1A2A4A',
    paddingVertical: 16,
    gap: 4,
    zIndex: 1,
  },
  footerText: {
    fontSize: 11,
    color: '#2A4A6A',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
});
